services:
  app_rust:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    image: app_rust:latest

  dummy_meili:
    build:
      context: ./deploy/meilisearch
    image: dummy_meili:latest

  dummy_redis:
    build:
      context: ./deploy/redis
    image: dummy_redis:latest
