services:
  # App: External
  meilisearch:
    build:
      context: ./deploy/meilisearch
    image: dummy_meili:latest

  redis:
    build:
      context: ./deploy/redis
    image: dummy_redis:latest

  # Monitoring
  grafana:
    build:
      context: ./monitor/grafana
    image: dummy_grafana:latest
